language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - yarn test
after_success:
  - yarn test --collectCoverage
  - yarn codecov
  - yarn semantic-release
